packages:
  - .
  - lambda

catalogs:
  ai:
    '@anthropic-ai/sdk': ^0.67.0
    '@google/generative-ai': ^0.24.1
    groq-sdk: ^0.34.0
    openai: ^6.7.0
    replicate: ^0.32.1
  auth:
    '@auth/mongodb-adapter': ^3.11.1
    '@auth/prisma-adapter': ^2.11.1
    bcryptjs: ^3.0.2
    jose: ^6.1.0
    next-auth: 5.0.0-beta.30
  aws:
    '@aws-sdk/client-cognito-identity-provider': ^3.922.0
    '@aws-sdk/client-lambda': ^3.922.0
    '@aws-sdk/client-secrets-manager': ^3.919.0
    aws-sdk: ^2.1400.0
  build:
    autoprefixer: ^10.4.0
    postcss: ^8.4.0
    tailwindcss: ^3.4.0
    tailwindcss-animate: ^1.0.7
  communication:
    '@sendgrid/eventwebhook': ^8.0.0
    '@sendgrid/mail': ^8.1.3
    twilio: ^5.3.5
  database:
    '@prisma/client': ^6.18.0
    mongodb: ^6.3.0
    prisma: ^6.18.0
  dev:
    dompurify: ^3.3.0
    husky: ^9.0.0
    isomorphic-dompurify: ^2.30.1
    lint-staged: ^16.2.6
    tsx: ^4.19.2
  forms:
    '@hookform/resolvers': ^3.10.0
    react-hook-form: ^7.65.0
    zod: ^3.25.76
  lint:
    '@eslint/eslintrc': ^3.3.1
    '@rushstack/eslint-patch': ^1.15.0
    '@typescript-eslint/eslint-plugin': ^7.0.0
    '@typescript-eslint/parser': ^7.0.0
    eslint: ^8.57.0
    eslint-config-next: ^15.5.4
    globals: ^16.5.0
    prettier: ^3.2.0
    prettier-plugin-tailwindcss: ^0.5.0
  markdown:
    gray-matter: ^4.0.3
    marked: ^16.4.1
    react-markdown: 10.1.0
    rehype-autolink-headings: ^7.1.0
    rehype-highlight: ^7.0.2
    rehype-slug: ^6.0.0
    remark-gfm: 4.0.1
  monitoring:
    '@sentry/nextjs': ^10
    '@vercel/analytics': ^1.4.1
    posthog-js: ^1.293.0
  react:
    next: ^15.5.4
    react: ^18.3.1
    react-dom: ^18.3.1
  state:
    '@tanstack/react-query': ^5.28.0
    superjson: ^2.2.1
    swr: ^2.3.6
    zustand: ^4.5.0
  storage:
    '@upstash/qstash': ^2.8.4
    '@upstash/redis': ^1.35.6
    '@vercel/kv': ^3.0.0
    ioredis: ^5.8.2
  testing:
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.0
    '@testing-library/user-event': ^14.6.1
    '@vitejs/plugin-react': ^5.1.0
    '@vitest/coverage-v8': ^1.3.0
    '@vitest/ui': ^4.0.4
    jest: ^30.2.0
    jsdom: ^27.0.1
    pixelmatch: ^7.1.0
    pngjs: ^7.0.0
    puppeteer: ^24.26.1
    ts-jest: ^29.4.5
    vitest: ^4.0.4
  trpc:
    '@trpc/client': ^10.45.0
    '@trpc/next': ^10.45.0
    '@trpc/react-query': ^10.45.0
    '@trpc/server': ^10.45.0
  typescript:
    '@types/bcryptjs': ^3.0.0
    '@types/dompurify': ^3.2.0
    '@types/jest': ^30.0.0
    '@types/node': ^24.9.1
    '@types/pngjs': ^6.0.5
    '@types/puppeteer': ^7.0.4
    '@types/react': ^18.2.0
    '@types/react-dom': ^18.2.0
    typescript: ^5.3.0
  ui:
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-checkbox': ^1.3.3
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-icons': ^1.3.2
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-progress': ^1.1.7
    '@radix-ui/react-radio-group': ^1.3.8
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slider': ^1.3.6
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-switch': ^1.2.6
    '@radix-ui/react-tabs': ^1.1.13
    '@radix-ui/react-toast': ^1.2.15
  ui-utils:
    class-variance-authority: ^0.7.0
    clsx: ^2.1.0
    date-fns: ^4.1.0
    lucide-react: ^0.344.0
    next-themes: ^0.2.1
    sonner: ^1.7.0
    tailwind-merge: ^3.3.1
    vaul: ^0.9.9
  utils:
    '@types/uuid': ^11.0.0
    dotenv: ^17.2.3
    nanoid: ^5.1.6
    uuid: ^13.0.0
    winston: ^3.18.3
    winston-daily-rotate-file: ^5.0.0
