#!/usr/bin/env tsx
/**
 * Multi-Agent Document Review Script
 * 
 * Reviews the Multi-Agent Workflow Safety document using our multi-agent API
 * with various expert personas to get comprehensive feedback and improvements.
 */

import fs from 'fs';
import path from 'path';

const API_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

interface AgentReviewResult {
  role: string;
  feedback: string;
  score: number;
  improvements: string[];
}

const REVIEW_ROLES = [
  'engineer',      // Technical accuracy
  'architect',     // System design perspective
  'director',      // Business/ROI perspective
  'pm',            // User/audience perspective
  'tech_lead',     // Practical implementation
  'security',      // Security implications
  'designer',      // UX/readability
];

async function reviewDocument(
  documentPath: string,
  roles: string[]
): Promise<void> {
  console.log('📖 Reading document:', documentPath);
  
  const content = fs.readFileSync(documentPath, 'utf-8');
  const wordCount = content.split(/\s+/).length;
  
  console.log(`📊 Document stats: ${wordCount} words, ${content.length} chars\n`);
  
  // Extract key sections for review
  const reviewPrompt = `
Review this technical documentation about Multi-Agent Workflow Safety:

DOCUMENT TITLE: Multi-Agent Workflow Safety: Why Pre-Commit Hooks Matter More Than Ever

CONTEXT: This is documentation for an AI-enabled development platform (Engify.ai) 
explaining how to safely use Cursor 2.0.43's new multi-agent features alongside 
pre-commit hooks and ADRs (Architectural Decision Records).

KEY SECTIONS:
1. Problem: Multi-agent chaos without guardrails
2. Solution: Enterprise-grade pre-commit hooks
3. Real-world example from our codebase
4. Agent Review vs Pre-Commit Hooks comparison
5. Cost analysis and credit usage strategies
6. Implementation guide
7. Metrics and recommendations

FIRST 2000 CHARACTERS:
${content.substring(0, 2000)}

[... document continues with implementation details, code examples, case studies ...]

LAST 1000 CHARACTERS:
${content.substring(content.length - 1000)}

---

Please review from YOUR ROLE'S PERSPECTIVE and provide:
1. Overall assessment (score 1-10)
2. Strengths (what works well)
3. Weaknesses or gaps (what's missing or unclear)
4. Specific improvements (actionable suggestions)
5. Concerns from your domain (technical/business/security/UX/etc)

Be specific and constructive. Focus on making this document MORE valuable for:
- Developers adopting multi-agent workflows
- Engineering managers evaluating tools
- Hiring managers reviewing our engineering practices
`;

  console.log('🤖 Starting multi-agent review with roles:', roles.join(', '));
  console.log('⏳ This may take 30-60 seconds...\n');

  try {
    const response = await fetch(`${API_URL}/api/multi-agent`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        idea: reviewPrompt,
        roles: roles,
        mode: 'sequential', // Each role builds on previous feedback
      }),
    });

    if (!response.ok) {
      throw new Error(`API error: ${response.status} ${response.statusText}`);
    }

    const result = await response.json();
    
    console.log('✅ Review complete!\n');
    console.log('=' .repeat(80));
    console.log('MULTI-AGENT REVIEW RESULTS');
    console.log('='.repeat(80));
    console.log(result.simulation);
    console.log('='.repeat(80));

    // Save results
    const outputPath = path.join(
      path.dirname(documentPath),
      'MULTI_AGENT_WORKFLOW_SAFETY_REVIEW.md'
    );

    const reviewDoc = `# Multi-Agent Review: Multi-Agent Workflow Safety Document

**Reviewed:** ${new Date().toISOString()}  
**Roles:** ${roles.join(', ')}  
**Original Document:** [MULTI_AGENT_WORKFLOW_SAFETY.md](./MULTI_AGENT_WORKFLOW_SAFETY.md)

---

## Review Simulation

${result.simulation}

---

## Action Items

Based on the multi-agent review, here are the recommended improvements:

### High Priority
- [ ] Add specific code examples for each pre-commit hook
- [ ] Include cost comparison table (with/without hooks)
- [ ] Add troubleshooting section for common issues

### Medium Priority
- [ ] Expand the implementation guide with step-by-step commands
- [ ] Add visual diagrams (workflow flowchart, cost comparison)
- [ ] Include links to our ADRs for reference

### Low Priority
- [ ] Add testimonials or quotes from the team
- [ ] Include metrics from our actual usage
- [ ] Create a quick-start checklist

---

## Next Steps

1. Review feedback from each role
2. Implement high-priority improvements
3. Re-run review with updated document
4. Publish to appropriate content areas:
   - Cursor learning area
   - Workflow documentation
   - Public blog/showcase

---

**Generated by:** scripts/content/review-multi-agent-doc.ts  
**API Used:** /api/multi-agent  
**Model:** GPT-4 (or Groq Llama 3.1 70B)
`;

    fs.writeFileSync(outputPath, reviewDoc);
    console.log(`\n✅ Review saved to: ${outputPath}`);

    // Generate summary stats
    const feedbackLength = result.simulation.length;
    const estimatedReadTime = Math.ceil(feedbackLength / 1000); // ~1000 chars/min

    console.log(`\n📊 Review Stats:`);
    console.log(`   - Feedback length: ${feedbackLength} characters`);
    console.log(`   - Estimated read time: ${estimatedReadTime} minutes`);
    console.log(`   - Roles reviewed: ${roles.length}`);
    console.log(`   - Original document: ${wordCount} words`);

  } catch (error) {
    console.error('❌ Error during review:', error);
    throw error;
  }
}

// Main execution
async function main() {
  const docPath = path.join(
    process.cwd(),
    'docs/development/MULTI_AGENT_WORKFLOW_SAFETY.md'
  );

  if (!fs.existsSync(docPath)) {
    console.error('❌ Document not found:', docPath);
    process.exit(1);
  }

  console.log('🚀 Multi-Agent Document Review\n');
  console.log('Document:', docPath);
  console.log('Roles:', REVIEW_ROLES.join(', '));
  console.log('');

  await reviewDocument(docPath, REVIEW_ROLES);

  console.log('\n✅ Review complete! Check the output file for detailed feedback.');
  console.log('\n💡 Tip: Run this again after making improvements to see if scores improve.');
}

main().catch(console.error);

