AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Secrets Manager infrastructure for Engify.ai application'

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, production)
    Default: production
    AllowedValues:
      - dev
      - staging
      - production

  SecretName:
    Type: String
    Description: Name for the application secrets
    Default: engify-ai/app-secrets

  EnableRotation:
    Type: String
    Description: Enable automatic secret rotation
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

Resources:
  # Main Application Secrets
  ApplicationSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: !Sub 'Engify.ai application secrets for ${Environment}'
      SecretString: |
        {
          "aiProviders": {
            "OPENAI_API_KEY": "",
            "ANTHROPIC_API_KEY": "",
            "GOOGLE_API_KEY": "",
            "GROQ_API_KEY": "",
            "REPLICATE_API_TOKEN": ""
          },
          "database": {
            "MONGODB_URI": ""
          },
          "auth": {
            "NEXTAUTH_SECRET": "",
            "NEXTAUTH_URL": "",
            "GOOGLE_CLIENT_ID": "",
            "GOOGLE_CLIENT_SECRET": "",
            "GITHUB_ID": "",
            "GITHUB_SECRET": ""
          },
          "email": {
            "SENDGRID_API_KEY": "",
            "SENDGRID_WEBHOOK_PUBLIC_KEY": ""
          },
          "sms": {
            "TWILIO_ACCOUNT_SID": "",
            "TWILIO_AUTH_TOKEN": "",
            "TWILIO_VERIFY_SERVICE_SID": ""
          },
          "queue": {
            "QSTASH_TOKEN": "",
            "CRON_SECRET": ""
          },
          "cache": {
            "UPSTASH_REDIS_REST_URL": "",
            "UPSTASH_REDIS_REST_TOKEN": "",
            "REDIS_PASSWORD": ""
          },
          "security": {
            "API_KEY_ENCRYPTION_KEY": "",
            "JIRA_TOKEN_ENCRYPTION_KEY": ""
          }
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Engify.ai
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for Vercel (or other external services) to access secrets
  SecretsAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'engify-ai-secrets-access-${Environment}'
      Description: Role for Vercel/external services to access Engify.ai secrets
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Sub '${AWS::StackName}-external-id'
      ManagedPolicyArns:
        - !Ref SecretsAccessPolicy
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Engify.ai

  # IAM Policy for reading secrets
  SecretsAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'engify-ai-secrets-read-${Environment}'
      Description: Policy to read Engify.ai application secrets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ReadApplicationSecrets
            Effect: Allow
            Action:
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
            Resource:
              - !Ref ApplicationSecrets
          - Sid: ListSecrets
            Effect: Allow
            Action:
              - 'secretsmanager:ListSecrets'
            Resource: '*'

  # IAM User for Vercel deployment (alternative to IAM Role)
  VercelDeploymentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'engify-ai-vercel-${Environment}'
      ManagedPolicyArns:
        - !Ref SecretsAccessPolicy
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Engify.ai
        - Key: Purpose
          Value: Vercel Deployment

  # Access Key for Vercel User (WARNING: Store securely!)
  VercelUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref VercelDeploymentUser
      Status: Active

  # Store Vercel access credentials in another secret
  VercelCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'engify-ai/vercel-credentials-${Environment}'
      Description: AWS credentials for Vercel deployment
      SecretString: !Sub |
        {
          "AWS_ACCESS_KEY_ID": "${VercelUserAccessKey}",
          "AWS_SECRET_ACCESS_KEY": "${VercelUserAccessKey.SecretAccessKey}",
          "AWS_REGION": "${AWS::Region}",
          "AWS_SECRETS_NAME": "${SecretName}"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Engify.ai
        - Key: Purpose
          Value: Vercel Credentials

  # CloudWatch Log Group for secret access auditing
  SecretsAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/secretsmanager/engify-ai/${Environment}'
      RetentionInDays: 30

  # CloudWatch Alarm for unauthorized access attempts
  UnauthorizedAccessAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'engify-ai-secrets-unauthorized-${Environment}'
      AlarmDescription: Alert on unauthorized secret access attempts
      MetricName: UnauthorizedAccessAttempts
      Namespace: AWS/SecretsManager
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

Outputs:
  SecretArn:
    Description: ARN of the application secrets
    Value: !Ref ApplicationSecrets
    Export:
      Name: !Sub '${AWS::StackName}-SecretArn'

  SecretName:
    Description: Name of the application secrets
    Value: !Ref SecretName
    Export:
      Name: !Sub '${AWS::StackName}-SecretName'

  SecretsAccessRoleArn:
    Description: ARN of the secrets access role
    Value: !GetAtt SecretsAccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AccessRoleArn'

  VercelAccessKeyId:
    Description: AWS Access Key ID for Vercel
    Value: !Ref VercelUserAccessKey

  VercelSecretAccessKey:
    Description: AWS Secret Access Key for Vercel (STORE SECURELY!)
    Value: !GetAtt VercelUserAccessKey.SecretAccessKey

  VercelCredentialsSecretArn:
    Description: ARN of the Vercel credentials secret
    Value: !Ref VercelCredentialsSecret
    Export:
      Name: !Sub '${AWS::StackName}-VercelCredentialsArn'

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region

  SetupInstructions:
    Description: Next steps for setup
    Value: !Sub |
      1. Update the secret values using the migration script:
         tsx scripts/aws/migrate-secrets.ts --secret-name ${SecretName} --region ${AWS::Region}

      2. Configure Vercel environment variables with these values:
         - AWS_ACCESS_KEY_ID: ${VercelUserAccessKey}
         - AWS_SECRET_ACCESS_KEY: (from VercelSecretAccessKey output)
         - AWS_REGION: ${AWS::Region}
         - AWS_SECRETS_NAME: ${SecretName}

      3. Deploy your application to Vercel

      See AWS_SECRETS_SETUP.md for detailed instructions.
